version: "3.1"

services:
  app:
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./app:/app
    command: sh -c "uvicorn main:app --host 0.0.0.0"
    depends_on:
      - postgresql
    env_file:
      - ./.env

  postgresql:
    image: postgres:latest
    ports:
      - 5432:5432
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  postgresql-test:
    image: postgres:latest
    ports:
      - 5433:5432
    env_file:
      - ./.env
    volumes:
      - postgres_data_test:/var/lib/postgresql/data
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - ./.env
    ports:
      - 5050:80
    depends_on:
      - postgresql
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    restart: always

volumes:
  postgres_data:
  postgres_data_test:
  pgadmin_data:
